name: Release

on:
    push:
      tags:
        - "v*"

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Setup Go
          uses: actions/setup-go@v5
        - uses: actions/checkout@v4
        - name: Auto Changelog
          uses: ardalanamini/auto-changelog@v4.0.1
          id: changelog
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            commit-types: |
                feat: New Features
                fix: Bug Fixes
                build: Build System & Dependencies
                perf: Performance Improvements
                docs: Documentation
                test: Tests
                refactor: Refactors
                chore: Chores
                ci: CI
                cd: CD
                style: Code Style
                revert: Reverts
        - name: Install dependencies
          run: go mod tidy
        - name: Run tests
          run: CI=true go test ./...
        - name: Build tailwindcss
          uses: actions/setup-node@v4
        - run: |
            cd src/tailwind && npm install && npm run build
        - name: Build
          run: |

            tag=$(git describe --tags --abbrev=0)

            # Linux build
            GOOS=linux GOARCH=amd64 go build -o bin/linux/aion-cli
            release_name_linux="aion-cli-$tag-linux"
            cd bin/linux && tar -czvf $release_name_linux.tar.gz aion-cli && cd ../..
            cp bin/linux/aion-cli ../testing/aion-cli


            GOOS=darwin GOARCH=amd64 go build -o bin/darwin/aion-cli
            release_name_macos="aion-cli-$tag-macos"
            cd bin/darwin && tar -czvf $release_name_macos.tar.gz aion-cli && cd ../..

            GOOS=windows GOARCH=amd64 go build -o bin/windows/aion-cli.exe
            release_name_windows="aion-cli-$tag-windows"
            cd bin/windows && tar -czvf $release_name_windows.tar.gz aion-cli.exe && cd ../..

            # Maybe create a arm build for macos

        - name: Test deterministic outcome of solver
          working-directory: testing
          run: |
            chmod +x aion-cli
            chmod +x deterministic.sh
            ./deterministic.sh
        - name: Release project
          uses: softprops/action-gh-release@v2
          with:
            body: ${{steps.changelog.outputs.changelog}}
            files: |
                 bin/linux/*.tar.gz
                 bin/darwin/*.tar.gz
                 bin/windows/*.tar.gz
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
            
