name: Test On Push

on:
    push:
    pull_request:
      branches: 
      - master

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Setup Go
          uses: actions/setup-go@v5
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: cd src && go mod tidy
        - name: Run tests
          run: go test -v ./...
